server:
  port: 8002

spring:
  application:
    name: service-oss

  servlet:
    multipart:
      # 上传单个文件的最大值
      max-file-size: 5MB
      max-request-size: 100MB

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.140.132:8848
        #server-addr: localhost:8848

  rabbitmq:
    virtual-host: /
    host: 192.168.140.132
    username: why
    password: 123
    port: 5672
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          # 开启消费者失败重试
          enabled: true
          # 初始的失败等待时间长1秒
          initial-interval: 1000
          # 失败等待时长的倍数
          multiplier: 2
          # 最大重试次数
          max-attempts: 3

aliyun:
  oss:
    file:
      # 地域节点
      endpoint: oss-cn-hangzhou.aliyuncs.com
      # accessKey
      keyid: LTAI5tMw2RMuuA1caZZJM6qf
      # accessSecret
      keysecret: ZyYXwFac07Xm2uw4DC8l8DoBBZDdft
      bucketname: why-server-bucket
